[Project]
baseURL = "https://appventure.me"

[Folders]
books = ["plom/summary.md", "yon/summary.md"]
booksFolder = "boks"
publicCopyFolders = ["js"]

[Shortlinks]
switch = "this-should-work-without-this-entry"
